-include Makefile.sim
-include Makefile.systemc
-include Makefile.vhdl
-include Makefile.synth
#-include ../../../lib/etc/Makefile.core
#-include ../../v2/dist/caph-unix/lib/etc/Makefile.core
-include Makefile.core 
